### ISSUE TITLE
Blocking on timeout

### ISSUE THREAD

**Issue by epilys** [sfackler/rust-native-tls#149]
This is how I initialize my socket before consuming it with `connector.connect`:

```
        let mut socket = TcpStream::connect(&addr)?;
        socket.set_read_timeout(Some(std::time::Duration::new(4, 0)))?;
        socket.set_write_timeout(Some(std::time::Duration::new(4, 0)))?;
        socket
            .set_nonblocking(true)
            .expect("set_nonblocking call failed");


```

I expect that this will mean it reads should never block. However if I leave that connection open for too long and then try a read it will block:
<details><summary>backtrace</summary>

```
#0    0x00007f6db798a7be in __libc_recv (flags=0, len=5, buf=0x556449e87b03, fd=7) at ../sysdeps/unix/sysv/linux/recv.c:28                                                                     [7/1904]
#1    0x00007f6db798a7be in __libc_recv (fd=7, buf=0x556449e87b03, len=5, flags=0) at ../sysdeps/unix/sysv/linux/recv.c:23
#2    0x0000556447e5ad6a in std::sys::unix::net::Socket::recv_with_flags () at src/libstd/sys/unix/net.rs:231
#3    0x0000556447e5ad6a in std::sys::unix::net::Socket::read () at src/libstd/sys/unix/net.rs:240
#4    0x0000556447e5ad6a in std::sys_common::net::TcpStream::read () at src/libstd/sys_common/net.rs:256
#5    0x0000556447e5ad6a in <std::net::tcp::TcpStream as std::io::Read>::read () at src/libstd/net/tcp.rs:570
#6    0x0000556447b21883 in openssl::ssl::bio::bread::{{closure}} ()
                         at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.28/src/ssl/bio.rs:113
#7    0x00005564478633f4 in core::ops::function::FnOnce::call_once ()
                         at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ops/function.rs:227
#8    0x0000556447b67d85 in <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once (self=std::panic::AssertUnwindSafe<closure-0> (openssl::ssl::bio::bread::closure-0 (0x7ffc4
51c2a70, 0x7ffc451c2a78)), _args=())
                         at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panic.rs:315
#9    0x0000556447b6db79 in std::panicking::try::do_call (data=0x7ffc451c29d0 "p*\034E\374\177\000")
                         at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:292
#10   0x0000556447e6da8a in __rust_maybe_catch_panic () at src/libpanic_unwind/lib.rs:80
#11   0x0000556447b6d536 in std::panicking::try (f=std::panic::AssertUnwindSafe<closure-0> (openssl::ssl::bio::bread::closure-0 (0x7ffc451c2a70, 0x7ffc451c2a78)))
                         at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:271
#12   0x0000556447b67eb5 in std::panic::catch_unwind (f=std::panic::AssertUnwindSafe<closure-0> (openssl::ssl::bio::bread::closure-0 (0x7ffc451c2a70, 0x7ffc451c2a78)))
                         at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panic.rs:394
#13   0x0000556447b214d3 in openssl::ssl::bio::bread (bio=0x556449f77dd0, buf=0x556449e87b03 "\267m\177", len=5)
                         at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.28/src/ssl/bio.rs:113
#14   0x00007f6db7ab2d8a in No symbol matches 0x00007f6db7ab2d8a. () at /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#15   0x00007f6db7ab1c33 in No symbol matches 0x00007f6db7ab1c33. () at /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#16   0x00007f6db7ab21e3 in BIO_read + 0x23 () at /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#17   0x00007f6db7d0162f in No symbol matches 0x00007f6db7d0162f. () at /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#18   0x00007f6db7d054ba in No symbol matches 0x00007f6db7d054ba. () at /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#19   0x00007f6db7d02e20 in No symbol matches 0x00007f6db7d02e20. () at /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#20   0x00007f6db7d0a265 in No symbol matches 0x00007f6db7d0a265. () at /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#21   0x00007f6db7d14cfa in No symbol matches 0x00007f6db7d14cfa. () at /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#22   0x00007f6db7d14e03 in SSL_read + 0x23 () at /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#23   0x0000556447d5d999 in openssl::ssl::SslRef::read (self=0x556449e92450, buf=&mut [u8](len: 1024) = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...})
                         at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.28/src/ssl/mod.rs:2375
#24   0x00005564479f6fc9 in openssl::ssl::SslStream<S>::ssl_read (self=0x7ffc451c4148, buf=&mut [u8](len: 1024) = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...})
                         at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.28/src/ssl/mod.rs:3414
#25   0x00005564479f5e7d in <openssl::ssl::SslStream<S> as std::io::Read>::read (self=0x7ffc451c4148, buf=&mut [u8](len: 1024) = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...})
                         at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.28/src/ssl/mod.rs:3556
#26   0x0000556447b73650 in <native_tls::imp::TlsStream<S> as std::io::Read>::read (self=0x7ffc451c4148, buf=&mut [u8](len: 1024) = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...})
                         at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/native-tls-0.2.3/src/imp/openssl.rs:396
#27   0x0000556447b1e310 in <native_tls::TlsStream<S> as std::io::Read>::read (self=0x7ffc451c4148, buf=&mut [u8](len: 1024) = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0--Type <RET> for more, q to quit, c to c
ontinue without paging--
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...})
```

</details>

**Comment by sfackler** [comment]
How is this issue related to the native-tls crate specifically?

Read and write timeouts are only relevant for blocking sockets. I have no idea what they do on nonblocking ones, but probably not whatever you are expecting.

**Comment by epilys** [comment]
> How is this issue related to the native-tls crate specifically?

I have no idea what's exactly is wrong, I'm trying to figure this out. The block is on the ssl read which is why I thought to ask here.

> Read and write timeouts are only relevant for blocking sockets. I have no idea what they do on nonblocking ones, but probably not whatever you are expecting.

I see, thank you.
