### ISSUE TITLE
Parallelism causes server unit tests to occasionally flake on OSX

### ISSUE THREAD

**Issue by jchien14** [sfackler/rust-native-tls#34]
Pretty stumped here..

If I add an additional unit test on a fresh checkout of master, I start getting two test failures:
```
---- test::server stdout ----
	thread 'test::server' panicked at 'Failure(Error { code: -9806, message: "connection closed via error" })', src/test.rs:76
stack backtrace:
   1:        0x109c13cbc - std::sys::imp::backtrace::tracing::imp::write::hb7ff6d5abd996ef4
   2:        0x109c16f9e - std::panicking::default_hook::{{closure}}::h53094adb345230b0
   3:        0x109c16b43 - std::panicking::default_hook::h5acf019c6eaf66af
   4:        0x109c17457 - std::panicking::rust_panic_with_hook::h8943f907023b7818
   5:        0x109c172b4 - std::panicking::begin_panic::h946820df60a04b85
   6:        0x109c17222 - std::panicking::begin_panic_fmt::h5face8a00b51b583
   7:        0x109b94c66 - native_tls::test::server::h3847131659cdb976
   8:        0x109bc70ce - <F as test::FnBox<T>>::call_box::h5c3bbb3b38d2930a
   9:        0x109c183ba - __rust_maybe_catch_panic
  10:        0x109bbb5c8 - std::panicking::try::do_call::h988206980d2b27fc
  11:        0x109c183ba - __rust_maybe_catch_panic
  12:        0x109bc230e - <F as alloc::boxed::FnBox<A>>::call_box::h2654ce5ce2ab7b8e
  13:        0x109c16664 - std::sys::imp::thread::Thread::new::thread_start::h4ad0b40513420e9c
  14:     0x7fff94e8aaaa - _pthread_body
  15:     0x7fff94e8a9f6 - _pthread_start

---- test::server_tls11_only stdout ----
	thread 'test::server_tls11_only' panicked at 'Failure(Error { code: -9806, message: "connection closed via error" })', src/test.rs:116
```

Removing the test causes things to pass again. Reproduced on 10.12.3.

This is the test I added for posterity:
```#[test]
fn connect_bad_hostname_ignored2() {
    let builder = p!(TlsConnector::builder());
    let builder = p!(builder.build());
    let s = p!(TcpStream::connect("google.com:443"));
    builder.danger_connect_without_providing_domain_for_certificate_verification_and_server_name_indication(s).unwrap();
}
``` 
(identical to an existing test but with a 2 in its name)

**Comment by jchien14** [comment]
This issue has now gone away but reproduced 100% of the time over at least 5 runs earlier (I was on a different network connection). Is it possible the tests are assuming something about the system configuration?

**Comment by sfackler** [comment]
I don't think it should be making any assumptions. You could try capturing the network traffic with Wireshark.

**Comment by jchien14** [comment]
Ah ha, it looks like they're failing due to certain tests running in parallel. Got back in a state where they were failing, and verified setting RUST_TEST_TASKS=1 fixed the issue.

**Comment by chaaz** [comment]
This also affects parallelism when tokio_tls is used to serve on multiple ports in the same thread.

```
  let mut lp = Core::new().unwrap();
  let loop1 = serve_https(lp.handle(), "cert1.pfx", 8443);
  let loop2 = serve_https(lp.handle(), "cert2.pfx", 8444);
  lp.run(loop1.join(loop2) ... ).unwrap();
```

```
$ curl -k https://localhost:8444
{"success": true}
$ curl -k https://localhost:8443
TLS connection failed: Error { code: -50, message: "One or more parameters passed to a function were not valid." }
curl: (35) Server aborted the SSL handshake
```

The provide patch in #54 fixes this.
